# Generated by Django 4.2.5 on 2023-09-13 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='промокод')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('percent', models.IntegerField(verbose_name='скидочный процент')),
                ('expiration_date', models.DateTimeField(verbose_name='годен до')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
            },
        ),
        migrations.CreateModel(
            name='UsedPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.promocode', verbose_name='промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'использованный промокод',
                'verbose_name_plural': 'использованные промокоды',
            },
        ),
    ]
