# Generated by Django 4.2.5 on 2023-09-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.IntegerField(verbose_name='кол-во'),
        ),
    ]
