# Generated by Django 4.2.5 on 2023-09-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_products_alter_order_date_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'заказ-товар', 'verbose_name_plural': 'заказы-товары'},
        ),
    ]
