# Generated by Django 4.2.5 on 2023-09-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='cnt_number',
            field=models.IntegerField(default=0, verbose_name='порядковый номер'),
        ),
    ]
